# General application settings
app:
  name: "Advanced DNS Enumeration Tool"
  version: "1.0.0"

# Logging configuration
logging:
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "logs/app.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Default paths
paths:
  wordlist: "data/subdomains.txt"
  resolvers: "data/resolvers.txt"
  tlds: "data/tlds.txt"

# Network settings
network:
  timeout: 10  # Timeout for network requests in seconds
  retries: 3   # Number of retries for failed network requests

# API keys (if needed)
api_keys:
  crtsh: null
  virustotal: ""
  securitytrails: "ot7yZ0WQ7qmp_jFB7AwzbRFnIh08cP4N"
  shodan: ""
  censys: ""
  threatcrowd: ""
